ARG DEBIAN_VERSION
FROM bearstech/golang-dev:${DEBIAN_VERSION}

ENV DEP_VERSION=0.5.3

RUN set -eux \
    &&  export http_proxy=${HTTP_PROXY} \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
            openssh-client \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* \
    &&  curl -qOL https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 \
		&&  mv dep-linux-amd64 /usr/local/bin/dep \
		&&  chmod +x /usr/local/bin/dep

WORKDIR /go

CMD ["dep", "ensure"]

# generated labels

ARG GIT_VERSION
ARG GIT_DATE
ARG BUILD_DATE

LABEL \
    com.bearstech.image.revision_date=${GIT_DATE} \
    org.opencontainers.image.authors=Bearstech \
    org.opencontainers.image.revision=${GIT_VERSION} \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.url=https://github.com/factorysh/docker-golang \
    org.opencontainers.image.source=https://github.com/factorysh/docker-golang/blob/${GIT_VERSION}/Dockerfile.dep
