FROM bearstech/golang-dev:stretch

USER root

RUN apt-get update && \
    apt-get install -y \
        openssh-client \
    && rm -rf /var/lib/apt/lists/*

ENV DEP_VERSION=0.4.1

RUN cd /tmp && curl -qOL https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64

RUN mv /tmp/dep-linux-amd64 /usr/local/bin/dep
RUN chmod +x /usr/local/bin/dep

USER go
